# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90e7538c4fb3e25e1d00716d958928edbec2fdf7d8851a11bcba907eba0381311f67df49b9bd49f23de0e9cf4400ed687d2ee6248e3c11f10b5a120c35a9e3a4

test:
  secret_key_base: 58924b8ba986cc8d0e4a9997df2e0e81a3b41f6a193878e5738d6073f324738f2764f88bc5ef5ae8e6bd713e53b2ce929ef985fd4ec822293cbc889b58400562

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
